// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/viriato-input/BottomSheet.tsx": () => import("../components/mockups/viriato-input/BottomSheet.tsx"),
  "./components/mockups/viriato-input/MenuPlus.tsx": () => import("../components/mockups/viriato-input/MenuPlus.tsx"),
  "./components/mockups/viriato-input/SwipeBar.tsx": () => import("../components/mockups/viriato-input/SwipeBar.tsx")
};
